// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQonz7JVRl5di8XkElbGtSffncJvmnCk8',
    appId: '1:216499397339:web:82a435983dea72068f62fe',
    messagingSenderId: '216499397339',
    projectId: 'appamigurumi-f5d6a',
    authDomain: 'appamigurumi-f5d6a.firebaseapp.com',
    storageBucket: 'appamigurumi-f5d6a.firebasestorage.app',
    measurementId: 'G-872WP45B5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNn114jamzd9AM5EcMfstdLGJtyTJ7hWA',
    appId: '1:216499397339:android:6394ee455d3bc15d8f62fe',
    messagingSenderId: '216499397339',
    projectId: 'appamigurumi-f5d6a',
    storageBucket: 'appamigurumi-f5d6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Tgj7mg9ZIsV9Lz7f30KwbCjPxgq_b-A',
    appId: '1:216499397339:ios:6f1c855f12cb8e658f62fe',
    messagingSenderId: '216499397339',
    projectId: 'appamigurumi-f5d6a',
    storageBucket: 'appamigurumi-f5d6a.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Tgj7mg9ZIsV9Lz7f30KwbCjPxgq_b-A',
    appId: '1:216499397339:ios:6f1c855f12cb8e658f62fe',
    messagingSenderId: '216499397339',
    projectId: 'appamigurumi-f5d6a',
    storageBucket: 'appamigurumi-f5d6a.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQonz7JVRl5di8XkElbGtSffncJvmnCk8',
    appId: '1:216499397339:web:82a435983dea72068f62fe',
    messagingSenderId: '216499397339',
    projectId: 'appamigurumi-f5d6a',
    authDomain: 'appamigurumi-f5d6a.firebaseapp.com',
    storageBucket: 'appamigurumi-f5d6a.firebasestorage.app',
    measurementId: 'G-872WP45B5F',
  );
}
